%MAKESTATE Makes a structure containing state information.
%
%Inputs:
%Outputs:
%
%makeState.m
%author:wreid
%date:20150218

function s = makeState(id,parentID,cost,alpha,beta,gamma,alphaDot,betaDot,gammaDot,phi,omega,dt,Dt)

    numIterations = round(Dt/dt);
    transitionArray = makeEmptyTransitionState();
    for i = 1:numIterations-1
        transitionArray = [transitionArray makeEmptyTransitionState()];
    end

    s = struct('id',id,...
                'parentID',parentID,...
                'cost',cost,...
                'alpha',alpha,...
                'beta',beta,...
                'gamma',gamma,...
                'alphaDot',alphaDot,...
                'betaDot',betaDot,...
                'gammaDot',gammaDot,...
                'phi',phi,...
                'omega',omega,...
                'transitionArray',transitionArray);
end